(node:420476) ExperimentalWarning: Fetch is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
warning: no blob constructor, cannot create blobs with mimetypes
warning: no BlobBuilder
Loading distutils
Loaded distutils
Python initialization complete
PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 359, in run_async
    await coroutine
  File "<exec>", line 3, in <module>
  File "/lib/python3.10/site-packages/pyodide/http.py", line 237, in pyfetch
    raise OSError(e.js_error.message) from None
OSError: fetch failed

    at new_error (/home/lesteve/dev/scikit-learn-tests-jupyterlite/node_modules/pyodide/pyodide.asm.js:10:218127)
    at wasm://wasm/021a6cb2:wasm-function[274]:0xdef7c
    at wasm://wasm/021a6cb2:wasm-function[378]:0xe37ae
    at method_call_trampoline (/home/lesteve/dev/scikit-learn-tests-jupyterlite/node_modules/pyodide/pyodide.asm.js:10:218041)
    at wasm://wasm/021a6cb2:wasm-function[942]:0x126317
    at wasm://wasm/021a6cb2:wasm-function[3192]:0x1f6f2e
    at wasm://wasm/021a6cb2:wasm-function[1855]:0x161a32
    at wasm://wasm/021a6cb2:wasm-function[947]:0x126827
    at wasm://wasm/021a6cb2:wasm-function[948]:0x126921
    at wasm://wasm/021a6cb2:wasm-function[949]:0x1269c4
    at wasm://wasm/021a6cb2:wasm-function[3018]:0x1e0697
    at wasm://wasm/021a6cb2:wasm-function[3015]:0x1da6a5
    at wasm://wasm/021a6cb2:wasm-function[950]:0x126a07
    at wasm://wasm/021a6cb2:wasm-function[3027]:0x1e248c
    at wasm://wasm/021a6cb2:wasm-function[3018]:0x1e00d9
    at wasm://wasm/021a6cb2:wasm-function[3015]:0x1da6a5
    at wasm://wasm/021a6cb2:wasm-function[950]:0x126a07
    at wasm://wasm/021a6cb2:wasm-function[373]:0xe347a
    at Object.Module.callPyObjectKwargs (/home/lesteve/dev/scikit-learn-tests-jupyterlite/node_modules/pyodide/pyodide.asm.js:10:119006)
    at Object.Module.callPyObject (/home/lesteve/dev/scikit-learn-tests-jupyterlite/node_modules/pyodide/pyodide.asm.js:10:119387)
    at Timeout.wrapper [as _onTimeout] (/home/lesteve/dev/scikit-learn-tests-jupyterlite/node_modules/pyodide/pyodide.asm.js:10:183751)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  __error_address: 10449112
}
